version: "3"
services:
  pineappletraderbot:
    build: .
    container_name: pineappletraderbot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_LOGGER_BOT_TOKEN=${TELEGRAM_LOGGER_BOT_TOKEN}
      - ADMIN_ID_STR=${ADMIN_ID_STR}
      - ADMIN_TINKOFF_TOKEN=${ADMIN_TINKOFF_TOKEN}
      - DELAY_STR=${DELAY_STR}
      - ADMIN_DB_CONNECTION_STRING=${ADMIN_DB_CONNECTION_STRING}
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:5432
